"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 08:10:37.479818
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("gate_hint", sa.String(length=16), nullable=True),
        sa.Column("context_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playground_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope_json", sa.JSON(), nullable=False),
        sa.Column("check_request_json", sa.JSON(), nullable=False),
        sa.Column("decision_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playground_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playground_runs_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("gate", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_version_id", sa.Integer(), nullable=True),
        sa.Column("live_version_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.String(length=16), nullable=False),
        sa.Column("business_case_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_case_id"],
            ["business_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["rule_versions.id"],
            name="fk_rules_current_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["live_version_id"], ["rule_versions.id"], name="fk_rules_live_version", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rules_gate"), ["gate"], unique=False)
        batch_op.create_index(batch_op.f("ix_rules_status"), ["status"], unique=False)

    op.create_table(
        "rule_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body_json", sa.JSON(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("jev_model", sa.String(length=32), nullable=True),
        sa.Column("translator_model", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "version", name="uq_rule_versions_rule_version"),
    )
    with op.batch_alter_table("rule_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_versions_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "test_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("check_request_json", sa.JSON(), nullable=False),
        sa.Column("expected_verdict", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_cases_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "test_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=True),
        sa.Column("rule_status", sa.String(length=16), nullable=False),
        sa.Column("jev_model", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("pass_count", sa.Integer(), nullable=False),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_estimate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_runs_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("test_case_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version_id", sa.Integer(), nullable=True),
        sa.Column("actual_verdict", sa.String(length=16), nullable=True),
        sa.Column("decision_json", sa.JSON(), nullable=True),
        sa.Column("jev_answers_json", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["rule_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["test_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_results_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_test_results_test_case_id"), ["test_case_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_results_test_case_id"))
        batch_op.drop_index(batch_op.f("ix_test_results_run_id"))

    op.drop_table("test_results")
    with op.batch_alter_table("test_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_runs_rule_id"))

    op.drop_table("test_runs")
    with op.batch_alter_table("test_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_cases_rule_id"))

    op.drop_table("test_cases")
    with op.batch_alter_table("rule_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_versions_rule_id"))

    op.drop_table("rule_versions")
    with op.batch_alter_table("rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rules_status"))
        batch_op.drop_index(batch_op.f("ix_rules_gate"))

    op.drop_table("rules")
    op.drop_table("settings")
    with op.batch_alter_table("playground_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playground_runs_created_at"))

    op.drop_table("playground_runs")
    op.drop_table("business_cases")
    # ### end Alembic commands ###
