/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Request
         * @description Evaluate against draft (latest versions), live (published versions) or chosen rules.
         */
        post: operations["evaluate_request_api_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples/packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Example Packs */
        get: operations["example_packs_api_examples_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples/packs/{name}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Example Pack
         * @description Create the pack's rules as drafts; rules whose ids already exist are skipped.
         */
        post: operations["load_example_pack_api_examples_packs__name__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playground/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playground Runs */
        get: operations["playground_runs_api_playground_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_api_rules__rule_id__get"];
        /**
         * Update Rule
         * @description Creates a new version unless the content is unchanged (`created_version: false`).
         */
        put: operations["update_rule_api_rules__rule_id__put"];
        post?: never;
        /**
         * Archive Rule
         * @description Soft delete: sets status to archived.
         */
        delete: operations["archive_rule_api_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Rule Status
         * @description `live` validates and pins the current version (a Jev version must be pinned).
         */
        post: operations["set_rule_status_api_rules__rule_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule Test Cases */
        get: operations["rule_test_cases_api_rules__rule_id__test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule Version */
        get: operations["get_rule_version_api_rules__rule_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Test Case */
        post: operations["create_test_case_api_test_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate
         * @description Business case -> draft rules + clarifications + generated tests (nothing is saved as a
         *     rule yet; the business case and result are stored).
         */
        post: operations["translate_api_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translate/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Translation */
        get: operations["get_translation_api_translate__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translate/{case_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Clarifications
         * @description Re-run the translation with the author's answers to the clarification questions.
         */
        post: operations["answer_clarifications_api_translate__case_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate/check-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Check Request
         * @description 422 if invalid; otherwise the normalized request.
         */
        post: operations["validate_check_request_api_validate_check_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate/rule-body": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Rule Body
         * @description Validate a candidate RuleBody; `live_problems` lists what blocks publication.
         */
        post: operations["validate_rule_body_api_validate_rule_body_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentInfo
         * @description Who is acting.
         */
        AgentInfo: {
            /** Id */
            id?: string | null;
            /**
             * Purpose
             * @description Summary of the agent's system prompt
             */
            purpose?: string | null;
        };
        /** AllPredicate */
        AllPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "all";
            /** Predicates */
            predicates: (components["schemas"]["ExistsPredicate"] | components["schemas"]["ComparePredicate"] | components["schemas"]["SetPredicate"] | components["schemas"]["RegexPredicate"] | components["schemas"]["MinLenPredicate"] | components["schemas"]["DomainPredicate"] | components["schemas"]["AllPredicate"] | components["schemas"]["AnyPredicate"] | components["schemas"]["NotPredicate"])[];
        };
        /** AnyPredicate */
        AnyPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "any";
            /** Predicates */
            predicates: (components["schemas"]["ExistsPredicate"] | components["schemas"]["ComparePredicate"] | components["schemas"]["SetPredicate"] | components["schemas"]["RegexPredicate"] | components["schemas"]["MinLenPredicate"] | components["schemas"]["DomainPredicate"] | components["schemas"]["AllPredicate"] | components["schemas"]["AnyPredicate"] | components["schemas"]["NotPredicate"])[];
        };
        /**
         * Bands
         * @description Thresholds, inclusive: value >= deny_at -> deny; >= escalate_at -> escalate; else allow.
         *
         *     escalate_at == deny_at disables the escalate band.
         */
        Bands: {
            /** Deny At */
            deny_at: number;
            /** Escalate At */
            escalate_at: number;
        };
        /**
         * CheckRequest
         * @description Only `gate` and `request` are required; rules declare what else they need.
         */
        CheckRequest: {
            agent?: components["schemas"]["AgentInfo"] | null;
            context?: components["schemas"]["Context"] | null;
            gate: components["schemas"]["Gate"];
            /** History */
            history?: components["schemas"]["HistoryItem"][] | null;
            /**
             * Reason
             * @description The agent's stated justification
             */
            reason?: string | null;
            request: components["schemas"]["RequestedAction"];
        };
        /** ChoiceAnswer */
        ChoiceAnswer: {
            /** Choice */
            choice: string;
            /** Confidence */
            confidence: number;
            /** Probabilities */
            probabilities?: {
                [key: string]: number;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice";
        };
        /**
         * ChoiceOutcome
         * @description Each option maps to a verdict; confidence below `min_confidence` escalates.
         */
        ChoiceOutcome: {
            /** Map */
            map: {
                [key: string]: components["schemas"]["Verdict"];
            };
            /**
             * Min Confidence
             * @default 0
             */
            min_confidence: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice";
        };
        /** ChoiceQuestion */
        ChoiceQuestion: {
            /**
             * Criteria
             * @description option -> description
             */
            criteria: {
                [key: string]: string;
            };
            /** Instructions */
            instructions: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice";
        };
        /** Clarification */
        Clarification: {
            /**
             * Id
             * @description Short snake_case id
             */
            id: string;
            /**
             * Options
             * @description 2-4 concrete answer options
             */
            options: string[];
            /**
             * Question
             * @description A specific question the author must answer
             */
            question: string;
            /**
             * Why
             * @description What is ambiguous and what changes depending on the answer
             */
            why: string;
        };
        /** ClarificationAnswers */
        ClarificationAnswers: {
            /**
             * Answers
             * @description Clarification id -> answer
             */
            answers: {
                [key: string]: string;
            };
        };
        /** ComparePredicate */
        ComparePredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "eq" | "gt" | "gte" | "lt" | "lte" | "ne";
            /** Path */
            path: string;
            /** Value */
            value: string | number | boolean | null;
        };
        /**
         * Context
         * @description Why the agent is acting, if the host provides it.
         */
        Context: {
            /** Recent Messages */
            recent_messages?: string[] | null;
            /** User Goal */
            user_goal?: string | null;
        };
        /** Decision */
        Decision: {
            /**
             * Gate Default Applied
             * @default false
             */
            gate_default_applied: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Rule Results */
            rule_results?: components["schemas"]["RuleResult"][];
            usage?: components["schemas"]["JevUsage"];
            verdict: components["schemas"]["Verdict"];
            versions: components["schemas"]["DecisionVersions"];
        };
        /** DecisionVersions */
        DecisionVersions: {
            /** Engine */
            engine: string;
            /** Jev Model */
            jev_model?: string | null;
            /** Policy */
            policy?: string | null;
            /** Rules */
            rules?: {
                [key: string]: number;
            };
            /**
             * Schema
             * @default 1
             */
            schema: number;
        };
        /**
         * DeterministicCheck
         * @description When `predicate` is true the rule's verdict is `verdict_when_true` and its Jev check
         *     is skipped; a deny short-circuits the whole decision. When false, the Jev check (if any)
         *     decides, otherwise the rule allows.
         */
        DeterministicCheck: {
            /** Predicate */
            predicate: components["schemas"]["ExistsPredicate"] | components["schemas"]["ComparePredicate"] | components["schemas"]["SetPredicate"] | components["schemas"]["RegexPredicate"] | components["schemas"]["MinLenPredicate"] | components["schemas"]["DomainPredicate"] | components["schemas"]["AllPredicate"] | components["schemas"]["AnyPredicate"] | components["schemas"]["NotPredicate"];
            verdict_when_true: components["schemas"]["Verdict"];
        };
        /** DomainPredicate */
        DomainPredicate: {
            /** Domains */
            domains: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "domain_in" | "domain_not_in";
            /** Path */
            path: string;
        };
        /** EvaluateRequest */
        EvaluateRequest: {
            check_request: components["schemas"]["CheckRequest"];
            scope?: components["schemas"]["EvaluateScope"];
        };
        /** EvaluateResponse */
        EvaluateResponse: {
            decision: components["schemas"]["Decision"];
            /**
             * Rules
             * @description The rules evaluated, keyed by id
             */
            rules: {
                [key: string]: components["schemas"]["RuleInfo"];
            };
            /** Run Id */
            run_id: string;
        };
        /**
         * EvaluateScope
         * @description draft: every non-archived rule at its latest version (previews unpublished edits).
         *     live: live rules at their published version (what enforcement runs).
         *     rules: the listed rules at their latest version.
         */
        EvaluateScope: {
            /**
             * Kind
             * @default draft
             * @enum {string}
             */
            kind: "draft" | "live" | "rules";
            /** Rule Ids */
            rule_ids?: string[];
        };
        /** Example */
        Example: {
            check_request: components["schemas"]["CheckRequest"];
            /** Description */
            description: string;
            expected_verdict?: components["schemas"]["Verdict"] | null;
            /** Id */
            id: string;
            /** Pack */
            pack?: string | null;
            /** Title */
            title: string;
        };
        /** ExistsPredicate */
        ExistsPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "exists" | "missing";
            /** Path */
            path: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * Gate
         * @enum {string}
         */
        Gate: "tool_call" | "egress" | "ingress";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Jev Configured */
            jev_configured: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * HistoryItem
         * @description A prior tool call in this session.
         */
        HistoryItem: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /** Result Summary */
            result_summary?: string | null;
            /** Tool */
            tool: string;
        };
        /** JevCheck */
        JevCheck: {
            /**
             * Model
             * @description Pinned version (jev-X.Y.Z) required for live rules
             * @default jev-latest
             */
            model: string;
            /** Outcomes */
            outcomes: {
                [key: string]: components["schemas"]["NoulOutcome"] | components["schemas"]["ChoiceOutcome"] | components["schemas"]["ScoreOutcome"];
            };
            /** Questions */
            questions: {
                [key: string]: components["schemas"]["NoulQuestion"] | components["schemas"]["ChoiceQuestion"] | components["schemas"]["ScoreQuestion"];
            };
            /**
             * State Template
             * @description CheckRequest paths sent to Jev as state; nothing else is
             */
            state_template: string[];
        };
        /** JevUsage */
        JevUsage: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** LLMUsage */
        LLMUsage: {
            /**
             * Cache Creation Input Tokens
             * @default 0
             */
            cache_creation_input_tokens: number;
            /**
             * Cache Read Input Tokens
             * @default 0
             */
            cache_read_input_tokens: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
        };
        /** MinLenPredicate */
        MinLenPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "min_len";
            /** Path */
            path: string;
            /** Value */
            value: number;
        };
        /** NotPredicate */
        NotPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "not";
            /** Predicate */
            predicate: components["schemas"]["ExistsPredicate"] | components["schemas"]["ComparePredicate"] | components["schemas"]["SetPredicate"] | components["schemas"]["RegexPredicate"] | components["schemas"]["MinLenPredicate"] | components["schemas"]["DomainPredicate"] | components["schemas"]["AllPredicate"] | components["schemas"]["AnyPredicate"] | components["schemas"]["NotPredicate"];
        };
        /** NoulAnswer */
        NoulAnswer: {
            /** Noul */
            noul: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noul";
        };
        /** NoulCriteria */
        NoulCriteria: {
            /** False */
            false: string;
            /** True */
            true: string;
        };
        /**
         * NoulOutcome
         * @description `high_is_bad`: bands apply to P(true). `low_is_bad`: bands apply to 1 - P(true).
         */
        NoulOutcome: {
            bands: components["schemas"]["Bands"];
            /**
             * Direction
             * @default high_is_bad
             * @enum {string}
             */
            direction: "high_is_bad" | "low_is_bad";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noul";
        };
        /** NoulQuestion */
        NoulQuestion: {
            criteria?: components["schemas"]["NoulCriteria"] | null;
            /** Instructions */
            instructions: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noul";
        };
        /** PackInfo */
        PackInfo: {
            /** Name */
            name: string;
            /** Rule Ids */
            rule_ids: string[];
        };
        /** PackLoadResult */
        PackLoadResult: {
            /** Created */
            created: string[];
            /** Skipped */
            skipped: string[];
        };
        /** PlaygroundRun */
        PlaygroundRun: {
            check_request: components["schemas"]["CheckRequest"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            decision: components["schemas"]["Decision"];
            /** Id */
            id: string;
            scope: components["schemas"]["EvaluateScope"];
        };
        /** Problem */
        Problem: {
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * QuestionResult
         * @description One Jev question's answer and the verdict it mapped to.
         */
        QuestionResult: {
            /** Answer */
            answer: components["schemas"]["NoulAnswer"] | components["schemas"]["ChoiceAnswer"] | components["schemas"]["ScoreAnswer"];
            /**
             * Band
             * @description Which band/branch was hit, e.g. 'deny (>= 0.7)'
             */
            band: string;
            /**
             * Value
             * @description The number compared with the bands (or the confidence)
             */
            value: number;
            verdict: components["schemas"]["Verdict"];
        };
        /** RegexPredicate */
        RegexPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "regex";
            /** Path */
            path: string;
            /** Pattern */
            pattern: string;
        };
        /**
         * RequestedAction
         * @description What the agent wants to do now.
         */
        RequestedAction: {
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
            /** Body */
            body?: string | {
                [key: string]: unknown;
            } | unknown[] | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "tool_call" | "external_call" | "content";
            /** Method */
            method?: string | null;
            /** Text */
            text?: string | null;
            /** Tool */
            tool?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * Requirement
         * @description Step 1+2: one atomic requirement and how it must be checked.
         */
        Requirement: {
            /**
             * Requirement
             * @description One atomic, testable requirement in plain words
             */
            requirement: string;
            /**
             * Routing
             * @description deterministic: numbers, dates, counts, exact matches, allowlists; judgment: needs understanding of meaning/intent; both: code guard + Jev judgment
             * @enum {string}
             */
            routing: "deterministic" | "judgment" | "both";
            /** Routing Reason */
            routing_reason: string;
            /**
             * Source Sentence
             * @description Exact sentence(s) from the business case
             */
            source_sentence: string;
        };
        /**
         * RuleBody
         * @description The versioned, hashed part of a rule: everything that can change a verdict.
         */
        RuleBody: {
            /**
             * Applies When
             * @description Cheap selector; absent = applies to every request at the gate
             */
            applies_when?: (components["schemas"]["ExistsPredicate"] | components["schemas"]["ComparePredicate"] | components["schemas"]["SetPredicate"] | components["schemas"]["RegexPredicate"] | components["schemas"]["MinLenPredicate"] | components["schemas"]["DomainPredicate"] | components["schemas"]["AllPredicate"] | components["schemas"]["AnyPredicate"] | components["schemas"]["NotPredicate"]) | null;
            deterministic?: components["schemas"]["DeterministicCheck"] | null;
            jev?: components["schemas"]["JevCheck"] | null;
            /** @description Verdict when Jev fails; absent = gate/severity default */
            on_error?: components["schemas"]["Verdict"] | null;
            /** @default escalate */
            on_missing: components["schemas"]["Verdict"];
            /**
             * Requires
             * @description Fields that must be present, else `on_missing`
             */
            requires?: string[];
            /** @default medium */
            severity: components["schemas"]["Severity"];
        };
        /** RuleBodyValidation */
        RuleBodyValidation: {
            /** Content Hash */
            content_hash?: string | null;
            /** Errors */
            errors: components["schemas"]["FieldError"][];
            /** Jev Model */
            jev_model?: string | null;
            /**
             * Live Problems
             * @default []
             */
            live_problems: string[];
            /** Valid */
            valid: boolean;
        };
        /** RuleCreate */
        RuleCreate: {
            body: components["schemas"]["RuleBody"];
            /** Explanation */
            explanation?: string | null;
            gate: components["schemas"]["Gate"];
            /**
             * Id
             * @description Slug; derived from name if omitted
             */
            id?: string | null;
            /** Name */
            name: string;
            provenance?: components["schemas"]["precheck__authoring__dto__Provenance"] | null;
            /** Source Text */
            source_text?: string | null;
        };
        /** RuleDetail */
        RuleDetail: {
            /**
             * Applies To Tools
             * @description Tool names from a simple `request.tool` eq/in selector, if any
             */
            applies_to_tools: string[];
            /**
             * Created By
             * @enum {string}
             */
            created_by: "user" | "agent";
            current: components["schemas"]["RuleVersion"];
            /** Current Version */
            current_version: number;
            gate: components["schemas"]["Gate"];
            /** Has Deterministic */
            has_deterministic: boolean;
            /** Has Jev */
            has_jev: boolean;
            /** Id */
            id: string;
            /** Jev Model */
            jev_model: string | null;
            live: components["schemas"]["RuleVersion"] | null;
            /** Live Version */
            live_version: number | null;
            /** Name */
            name: string;
            /** Requires */
            requires: string[];
            severity: components["schemas"]["Severity"];
            /** Source Text */
            source_text: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "live" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** RuleInfo */
        RuleInfo: {
            body: components["schemas"]["RuleBody"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "live" | "archived";
            /** Version */
            version: number;
        };
        /** RuleResult */
        RuleResult: {
            /** Error */
            error?: string | null;
            /** Jev */
            jev?: {
                [key: string]: components["schemas"]["QuestionResult"];
            };
            /** Matched */
            matched: boolean;
            /** Missing Fields */
            missing_fields?: string[];
            /** Predicate Inputs */
            predicate_inputs?: {
                [key: string]: unknown;
            };
            /** Predicate Result */
            predicate_result?: boolean | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version?: number | null;
            /** Source */
            source?: ("missing_fields" | "deterministic" | "jev" | "error" | "no_verdict") | null;
            verdict?: components["schemas"]["Verdict"] | null;
        };
        /**
         * RuleSpec
         * @description A rule as authored in YAML/JSON (rule packs, import/export).
         */
        RuleSpec: {
            body: components["schemas"]["RuleBody"];
            /** Explanation */
            explanation?: string | null;
            gate: components["schemas"]["Gate"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Text */
            source_text?: string | null;
            /** Tests */
            tests?: components["schemas"]["TestCaseSpec"][];
        };
        /** RuleStatusChange */
        RuleStatusChange: {
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "live" | "archived";
        };
        /** RuleSummary */
        RuleSummary: {
            /**
             * Applies To Tools
             * @description Tool names from a simple `request.tool` eq/in selector, if any
             */
            applies_to_tools: string[];
            /**
             * Created By
             * @enum {string}
             */
            created_by: "user" | "agent";
            /** Current Version */
            current_version: number;
            gate: components["schemas"]["Gate"];
            /** Has Deterministic */
            has_deterministic: boolean;
            /** Has Jev */
            has_jev: boolean;
            /** Id */
            id: string;
            /** Jev Model */
            jev_model: string | null;
            /** Live Version */
            live_version: number | null;
            /** Name */
            name: string;
            /** Requires */
            requires: string[];
            severity: components["schemas"]["Severity"];
            /** Source Text */
            source_text: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "live" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RuleUpdate */
        RuleUpdate: {
            body: components["schemas"]["RuleBody"];
            /** Explanation */
            explanation?: string | null;
            /** Name */
            name?: string | null;
            provenance?: components["schemas"]["precheck__authoring__dto__Provenance"] | null;
            /** Source Text */
            source_text?: string | null;
        };
        /** RuleUpdateResult */
        RuleUpdateResult: {
            /**
             * Applies To Tools
             * @description Tool names from a simple `request.tool` eq/in selector, if any
             */
            applies_to_tools: string[];
            /**
             * Created By
             * @enum {string}
             */
            created_by: "user" | "agent";
            /**
             * Created Version
             * @description False when the edit was a no-op (same content)
             */
            created_version: boolean;
            current: components["schemas"]["RuleVersion"];
            /** Current Version */
            current_version: number;
            gate: components["schemas"]["Gate"];
            /** Has Deterministic */
            has_deterministic: boolean;
            /** Has Jev */
            has_jev: boolean;
            /** Id */
            id: string;
            /** Jev Model */
            jev_model: string | null;
            live: components["schemas"]["RuleVersion"] | null;
            /** Live Version */
            live_version: number | null;
            /** Name */
            name: string;
            /** Requires */
            requires: string[];
            severity: components["schemas"]["Severity"];
            /** Source Text */
            source_text: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "live" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** RuleVersion */
        RuleVersion: {
            body: components["schemas"]["RuleBody"];
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Jev Model */
            jev_model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Rule Id */
            rule_id: string;
            /** Source Text */
            source_text?: string | null;
            /** Translator Model */
            translator_model?: string | null;
            /** Version */
            version: number;
        };
        /** ScoreAnswer */
        ScoreAnswer: {
            /** Confidence */
            confidence: number;
            /** Legend */
            legend?: {
                [key: string]: string;
            };
            /** Probabilities */
            probabilities?: {
                [key: string]: number;
            };
            /** Score */
            score: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "score";
        };
        /**
         * ScoreOutcome
         * @description Bands on the expected score (a float in [0, levels-1]); low confidence escalates.
         */
        ScoreOutcome: {
            bands: components["schemas"]["Bands"];
            /**
             * Min Confidence
             * @default 0
             */
            min_confidence: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "score";
        };
        /** ScoreQuestion */
        ScoreQuestion: {
            /**
             * Criteria
             * @description level descriptions, level 0 first
             */
            criteria: string[];
            /** Instructions */
            instructions: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "score";
        };
        /** SetPredicate */
        SetPredicate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "in" | "not_in";
            /** Path */
            path: string;
            /** Values */
            values: (string | number | boolean | null)[];
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high";
        /** TestCase */
        TestCase: {
            check_request: components["schemas"]["CheckRequest"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            expected_verdict: components["schemas"]["Verdict"];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "user" | "generated" | "playground";
            /** Rule Id */
            rule_id: string | null;
        };
        /** TestCaseCreate */
        TestCaseCreate: {
            check_request: components["schemas"]["CheckRequest"];
            expected_verdict: components["schemas"]["Verdict"];
            /** Name */
            name: string;
            /**
             * Origin
             * @default user
             * @enum {string}
             */
            origin: "user" | "generated" | "playground";
            /**
             * Rule Id
             * @description None = policy-wide case
             */
            rule_id?: string | null;
        };
        /**
         * TestCaseSpec
         * @description A golden-set example: a check request and the verdict the rule(s) should give.
         */
        TestCaseSpec: {
            check_request: components["schemas"]["CheckRequest"];
            expected_verdict: components["schemas"]["Verdict"];
            /** Name */
            name: string;
            /**
             * Origin
             * @default user
             * @enum {string}
             */
            origin: "user" | "generated" | "playground";
        };
        /** TranslateInput */
        TranslateInput: {
            /** Agent Purpose */
            agent_purpose?: string | null;
            /**
             * Answers
             * @description Clarification id -> answer
             */
            answers?: {
                [key: string]: string;
            };
            /**
             * Domains
             * @description Our own / allowlisted domains
             */
            domains?: string[];
            gate_hint?: components["schemas"]["Gate"] | null;
            /**
             * Text
             * @description The business case, in prose
             */
            text: string;
            /**
             * Tools
             * @description Tool catalog the agent has
             */
            tools?: string[];
        };
        /** TranslateResponse */
        TranslateResponse: {
            /** Business Case Id */
            business_case_id: string;
            result: components["schemas"]["TranslationResult"];
        };
        /** TranslatedRule */
        TranslatedRule: {
            spec: components["schemas"]["RuleSpec"];
            /** Warnings */
            warnings?: components["schemas"]["TranslationWarning"][];
        };
        /** TranslatedTest */
        TranslatedTest: {
            /** Kind */
            kind: string;
            /** Rule Id */
            rule_id: string;
            test: components["schemas"]["TestCaseSpec"];
        };
        /** TranslationResult */
        TranslationResult: {
            /** Clarifications */
            clarifications?: components["schemas"]["Clarification"][];
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Errors
             * @description Problems left after repair
             */
            errors?: string[];
            provenance: components["schemas"]["precheck__translator__pipeline__Provenance"];
            /**
             * Repair Rounds
             * @default 0
             */
            repair_rounds: number;
            /** Requirements */
            requirements?: components["schemas"]["Requirement"][];
            /** Rules */
            rules?: components["schemas"]["TranslatedRule"][];
            /**
             * Status
             * @description translated | needs_clarification | failed
             */
            status: string;
            /** Tests */
            tests?: components["schemas"]["TranslatedTest"][];
            usage?: components["schemas"]["LLMUsage"];
            /** Warnings */
            warnings?: components["schemas"]["TranslationWarning"][];
        };
        /** TranslationWarning */
        TranslationWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Rule Id */
            rule_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "allow" | "deny" | "escalate";
        /** VersionSummary */
        VersionSummary: {
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at: string | null;
            /** Is Current */
            is_current: boolean;
            /** Is Live */
            is_live: boolean;
            /** Jev Model */
            jev_model: string | null;
            /** Version */
            version: number;
        };
        /** Provenance */
        precheck__authoring__dto__Provenance: {
            /** Prompt Version */
            prompt_version?: string | null;
            /** Translator Model */
            translator_model?: string | null;
        };
        /** Provenance */
        precheck__translator__pipeline__Provenance: {
            /**
             * Code Version
             * @default 0.1.0
             */
            code_version: string;
            /** Prompt Version */
            prompt_version: string;
            /** Translator Model */
            translator_model: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evaluate_request_api_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Example"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    example_packs_api_examples_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackInfo"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    load_example_pack_api_examples_packs__name__load_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackLoadResult"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    playground_runs_api_playground_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundRun"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_rules_api_rules_get: {
        parameters: {
            query?: {
                gate?: components["schemas"]["Gate"] | null;
                /** @description Default hides archived */
                status?: ("draft" | "live" | "archived" | "all") | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSummary"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_rule_api_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_rule_api_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    update_rule_api_rules__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleUpdateResult"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    archive_rule_api_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    set_rule_status_api_rules__rule_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleStatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rule_test_cases_api_rules__rule_id__test_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_rule_version_api_rules__rule_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleVersion"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    create_test_case_api_test_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCase"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    translate_api_translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_translation_api_translate__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    answer_clarifications_api_translate__case_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarificationAnswers"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation problem */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    validate_check_request_api_validate_check_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_rule_body_api_validate_rule_body_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleBodyValidation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
