import type { components } from './schema'

type S = components['schemas']

export type Gate = S['Gate']
export type Verdict = S['Verdict']
export type Severity = S['Severity']
export type RuleStatus = S['RuleSummary']['status']
export type RuleBody = S['RuleBody']
export type RuleSummary = S['RuleSummary']
export type RuleDetail = S['RuleDetail']
export type RuleVersion = S['RuleVersion']
export type RuleCreate = S['RuleCreate']
export type RuleUpdate = S['RuleUpdate']
export type JevCheck = S['JevCheck']
export type JevQuestion = JevCheck['questions'][string]
export type Outcome = JevCheck['outcomes'][string]
export type NoulQuestion = S['NoulQuestion']
export type ChoiceQuestion = S['ChoiceQuestion']
export type ScoreQuestion = S['ScoreQuestion']
export type NoulOutcome = S['NoulOutcome']
export type ChoiceOutcome = S['ChoiceOutcome']
export type ScoreOutcome = S['ScoreOutcome']
export type Bands = S['Bands']
export type DeterministicCheck = S['DeterministicCheck']
export type Predicate = NonNullable<RuleBody['applies_when']>
export type Problem = S['Problem']
export type FieldError = S['FieldError']

export const GATES: Gate[] = ['tool_call', 'egress', 'ingress']
export const VERDICTS: Verdict[] = ['allow', 'escalate', 'deny']
export const SEVERITIES: Severity[] = ['low', 'medium', 'high']

export type CheckRequest = S['CheckRequest']
export type Decision = S['Decision']
export type RuleResult = S['RuleResult']
export type QuestionResult = S['QuestionResult']
export type EvaluateScope = S['EvaluateScope']
export type EvaluateResponse = S['EvaluateResponse']
export type RuleInfo = S['RuleInfo']
export type PlaygroundRun = S['PlaygroundRun']
export type Example = S['Example']
export type TestCase = S['TestCase']
export type TestCaseCreate = S['TestCaseCreate']

export type TranslateInput = S['TranslateInput']
export type TranslateResponse = S['TranslateResponse']
export type TranslationResult = S['TranslationResult']
export type TranslatedRule = S['TranslatedRule']
export type TranslatedTest = S['TranslatedTest']
export type TranslationWarning = S['TranslationWarning']
export type Clarification = S['Clarification']
export type Requirement = S['Requirement']
export type RuleSpec = S['RuleSpec']
export type SaveTranslation = S['SaveTranslation']
export type RefineResult = S['RefineResult']

export type TestRun = S['TestRun']
export type TestResult = S['TestResult']
export type CalibrationResult = S['CalibrationResult']
export type QuestionCalibration = S['QuestionCalibration']

export type PublishResult = S['PublishResult']
export type RuleDiff = S['RuleDiff']
export type PolicyVersion = S['PolicyVersion']
export type UpgradeReport = S['UpgradeReport']
export type ImportResult = S['ImportResult']
