"""The canonical contracts (single source of truth for API, engine, translator, UI)."""

from precheck.schema.check_request import (
    AgentInfo,
    CheckRequest,
    Context,
    HistoryItem,
    RequestedAction,
    RequestKind,
)
from precheck.schema.common import (
    SCHEMA_VERSION,
    VERDICT_RANK,
    Gate,
    RuleId,
    RuleStatus,
    Severity,
    Verdict,
    strictest,
)
from precheck.schema.hashing import canonical_json, content_hash
from precheck.schema.jev import (
    Bands,
    ChoiceAnswer,
    ChoiceOutcome,
    ChoiceQuestion,
    JevAnswer,
    JevCheck,
    JevQuestion,
    JevUsage,
    NoulAnswer,
    NoulCriteria,
    NoulOutcome,
    NoulQuestion,
    Outcome,
    ScoreAnswer,
    ScoreOutcome,
    ScoreQuestion,
)
from precheck.schema.paths import MISSING, CheckPath, resolve
from precheck.schema.predicate import (
    Predicate,
    describe_predicate,
    evaluate_predicate,
    predicate_paths,
)
from precheck.schema.rule import (
    Decision,
    DecisionVersions,
    DeterministicCheck,
    QuestionResult,
    Rule,
    RuleBody,
    RulePack,
    RuleResult,
    RuleSpec,
    RuleVersion,
    TestCaseSpec,
    live_problems,
)

__all__ = [
    "MISSING",
    "SCHEMA_VERSION",
    "VERDICT_RANK",
    "AgentInfo",
    "Bands",
    "CheckPath",
    "CheckRequest",
    "ChoiceAnswer",
    "ChoiceOutcome",
    "ChoiceQuestion",
    "Context",
    "Decision",
    "DecisionVersions",
    "DeterministicCheck",
    "Gate",
    "HistoryItem",
    "JevAnswer",
    "JevCheck",
    "JevQuestion",
    "JevUsage",
    "NoulAnswer",
    "NoulCriteria",
    "NoulOutcome",
    "NoulQuestion",
    "Outcome",
    "Predicate",
    "QuestionResult",
    "RequestKind",
    "RequestedAction",
    "Rule",
    "RuleBody",
    "RuleId",
    "RulePack",
    "RuleResult",
    "RuleSpec",
    "RuleStatus",
    "RuleVersion",
    "ScoreAnswer",
    "ScoreOutcome",
    "ScoreQuestion",
    "Severity",
    "TestCaseSpec",
    "Verdict",
    "canonical_json",
    "content_hash",
    "describe_predicate",
    "evaluate_predicate",
    "live_problems",
    "predicate_paths",
    "resolve",
    "strictest",
]
