"""lab decisions and escalations

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 10:14:59.745514
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escalations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session", sa.String(length=128), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("args_hash", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("check_request_json", sa.JSON(), nullable=True),
        sa.Column("decision_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("escalations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_escalations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_escalations_session"), ["session"], unique=False)
        batch_op.create_index(batch_op.f("ix_escalations_status"), ["status"], unique=False)

    op.create_table(
        "lab_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session", sa.String(length=128), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("gate", sa.String(length=16), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("forwarded", sa.Boolean(), nullable=False),
        sa.Column("escalation_id", sa.String(length=36), nullable=True),
        sa.Column("check_request_json", sa.JSON(), nullable=True),
        sa.Column("decision_json", sa.JSON(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lab_decisions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lab_decisions_session"), ["session"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_decisions_session"))
        batch_op.drop_index(batch_op.f("ix_lab_decisions_created_at"))

    op.drop_table("lab_decisions")
    with op.batch_alter_table("escalations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_escalations_status"))
        batch_op.drop_index(batch_op.f("ix_escalations_session"))
        batch_op.drop_index(batch_op.f("ix_escalations_created_at"))

    op.drop_table("escalations")
    # ### end Alembic commands ###
