"""lab runs

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 10:26:38.312069
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lab_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("scenario_id", sa.String(length=128), nullable=True),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("transcript_json", sa.JSON(), nullable=True),
        sa.Column("final_text", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lab_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_runs_scenario_id"), ["scenario_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lab_runs_started_at"), ["started_at"], unique=False)

    op.create_table(
        "lab_run_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("step_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["lab_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "idx", name="uq_lab_run_steps_run_idx"),
    )
    with op.batch_alter_table("lab_run_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lab_run_steps_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_run_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_run_steps_run_id"))

    op.drop_table("lab_run_steps")
    with op.batch_alter_table("lab_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lab_runs_started_at"))
        batch_op.drop_index(batch_op.f("ix_lab_runs_scenario_id"))

    op.drop_table("lab_runs")
    # ### end Alembic commands ###
